define ["backbone"], (Backbone) ->
  class Phage extends Backbone.Model

    sync: (method, model, options) ->
      options || options = {}
      options.timeout = 8000
      options.dataType = 'jsonp'
      options.validate = true
      return Backbone.sync(method, model, options)

    defaults:
      ppa: ''
      name: ''
      stocks: ''
      sample_type: ''
      parent_ppa: ''
      plaque_archive_id: ''
      external_source_id: ''
      host_isolation: ''
      host_lysate: ''
      host_all: ''
      experiment_type: ''
      source_type: ''
      source_date: ''
      source_comments: ''
      source_poc: ''
      morphotype_em: ''
      morphotype_genome: ''
      cluster_id_kt: ''
      cluster_id_ktandb: ''
      micrograph_directory: ''
      plaque_image: ''
      density_iodixanol: ''
      density_cscl: ''
      illumina: ''
      genome_length: ''
      seq_gbk: ''
      seq_gen: ''
      seq_fna: ''
      seq_faa: ''
      annotation_file: ''
      ncbi_accesseion: ''
      pac_bio: ''
    parse: (data) ->
      ppa: data.ppa || ''
      name: data.name || ''
      stocks: data.stocks || ''
      sample_type: data.sample_type || ''
      parent_ppa: data.parent_ppa || ''
      plaque_archive_id: data.plaque_archive_id || ''
      external_source_id: data.external_source_id || ''
      host_isolation: data.host_isolation || ''
      host_lysate: data.host_lysate || ''
      host_all: data.host_all || ''
      experiment_type: data.experiment_type || ''
      source_type: data.source_type || ''
      source_date: data.source_date || ''
      source_comments: data.source_comments || ''
      source_poc: data.source_poc || ''
      morphotype_em: data.morphotype_em || ''
      morphotype_genome: data.morphotype_genome || ''
      cluster_id_kt: data.cluster_id_kt || ''
      cluster_id_ktandb: data.cluster_id_ktandb || ''
      micrograph_directory: data.micrograph_directory || ''
      plaque_image: data.plaque_image || ''
      density_iodixanol: data.density_iodixanol || ''
      density_cscl: data.density_cscl || ''
      illumina: data.illumina || ''
      genome_length: data.genome_length || ''
      seq_gbk: data.seq_gbk || ''
      seq_gen: data.seq_gen || ''
      seq_fna: data.seq_fna || ''
      seq_faa: data.seq_faa || ''
      annotation_file: data.annotation_file || ''
      ncbi_accesseion: data.ncbi_accesseion || ''
      pac_bio: data.pac_bio || ''
